// <auto-generated />
using System;
using MaintenancePlanning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaintenancePlanning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintenancePlanningDbContext))]
    partial class MaintenancePlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planning")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("FunctionalLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetNumber")
                        .IsUnique();

                    b.HasIndex("FunctionalLocationId");

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("assets", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AssetNumber = "AS-1000",
                            Criticality = "high",
                            FunctionalLocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ImportedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 1, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Primary Pump Set",
                            SourceId = "ASSET-1000",
                            SourceSystem = "synthetic-source",
                            SourceUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.FunctionalLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentSourceId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("functional_locations", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "AREA-1000",
                            ImportedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 1, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Area 1000",
                            SourceId = "FL-1000",
                            SourceSystem = "synthetic-source",
                            SourceUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.IntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("IntegrationImportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Readiness")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ValidationIssueCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("WorkOrderSourceId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("IntegrationImportId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("integration_events", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CorrelationId = "seed-correlation-1000",
                            Disposition = "accepted",
                            EventId = "seed-event-1000",
                            EventType = "work-order-imported",
                            IdempotencyKey = "seed-work-order-event-1000",
                            IntegrationImportId = new Guid("90000000-0000-0000-0000-000000000001"),
                            OccurredAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PayloadHash = "sha256-seed-event",
                            PublishedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 1, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Readiness = "Ready",
                            RecordedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 4, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SchemaVersion = "1.0",
                            SourceRecordId = "WO-1000",
                            SourceSystem = "synthetic-source",
                            Status = "Accepted",
                            WorkOrderSourceId = "WO-1000"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.IntegrationImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("IgnoredDuplicateCount")
                        .HasColumnType("int");

                    b.Property<int>("IgnoredStaleCount")
                        .HasColumnType("int");

                    b.Property<string>("ImportKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReceivedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("integration_imports", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            AcceptedCount = 2,
                            CompletedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 4, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdempotencyKey = "seed-work-orders-2026-01-15",
                            IgnoredDuplicateCount = 0,
                            IgnoredStaleCount = 0,
                            ImportKind = "work-orders",
                            ReceivedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReceivedCount = 2,
                            RejectedCount = 0,
                            RequestHash = "sha256-seed-work-orders",
                            SourceSystem = "synthetic-source",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.MajorEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("FunctionalLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReadinessIssueCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FunctionalLocationId");

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("major_events", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AssetId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EndsAtUtc = new DateTimeOffset(new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "access-window",
                            FunctionalLocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ImportedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 4, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Severity = "medium",
                            SourceId = "EVT-1000",
                            SourceSystem = "synthetic-source",
                            StartsAtUtc = new DateTimeOffset(new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Shared access window"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAtUtc");

                    b.ToTable("outbox_events", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AggregateId = new Guid("60000000-0000-0000-0000-000000000001"),
                            AggregateType = "WorkOrderPackage",
                            AttemptCount = 0,
                            AvailableAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 11, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 11, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "planning.package.recommended",
                            PayloadJson = "{\"eventType\":\"planning.package.recommended\",\"packageNumber\":\"PKG-1000\"}",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PackageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FitReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkOrderPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderPackageId", "WorkOrderId")
                        .IsUnique();

                    b.ToTable("package_items", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            FitReason = "Work order is ready and aligns with the access window.",
                            Sequence = 1,
                            WorkOrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                            WorkOrderPackageId = new Guid("60000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PlannerDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkOrderPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderPackageId");

                    b.ToTable("planner_decisions", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            DecidedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 12, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DecidedBy = "local-review",
                            Decision = "Deferred",
                            Notes = "Synthetic seed decision for local review.",
                            ReasonCode = "awaiting-review",
                            WorkOrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                            WorkOrderPackageId = new Guid("60000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PlanningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("HorizonEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("HorizonStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RunNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("RunNumber")
                        .IsUnique();

                    b.ToTable("planning_runs", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CompletedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 11, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Horizon = "two-week",
                            HorizonEndUtc = new DateTimeOffset(new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HorizonStartUtc = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdempotencyKey = "seed-planning-run-2026-01-15",
                            RequestedBy = "local-review",
                            RequestHash = "sha256-seed-planning-run",
                            RunNumber = "RUN-1000",
                            StartedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid?>("FunctionalLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Readiness")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReadinessIssueCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ReadinessIssueDetail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RequiredStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ScheduledStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourcePayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FunctionalLocationId");

                    b.HasIndex("Readiness");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("work_orders", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AssetId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DueAtUtc = new DateTimeOffset(new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedHours = 8.5m,
                            FunctionalLocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ImportedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 2, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "high",
                            Readiness = "Ready",
                            RequiredStartUtc = new DateTimeOffset(new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceId = "WO-1000",
                            SourcePayloadHash = "sha256-ready-work-order",
                            SourceSystem = "synthetic-source",
                            SourceUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "ReadyForPlanning",
                            Title = "Replace pump seals",
                            WorkOrderNumber = "WO-1000",
                            WorkType = "corrective"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AssetId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DueAtUtc = new DateTimeOffset(new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionalLocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ImportedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "medium",
                            Readiness = "NeedsReview",
                            ReadinessIssueCode = "missing-estimate",
                            ReadinessIssueDetail = "Estimated effort is required before packaging.",
                            RequiredStartUtc = new DateTimeOffset(new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceId = "WO-1001",
                            SourcePayloadHash = "sha256-review-work-order",
                            SourceSystem = "synthetic-source",
                            SourceUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Imported",
                            Title = "Inspect standby valve",
                            WorkOrderNumber = "WO-1001",
                            WorkType = "preventive"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrderPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("PackageNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("PlannedEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PlannedStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlanningRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecommendationRationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("PackageNumber")
                        .IsUnique();

                    b.HasIndex("PlanningRunId");

                    b.ToTable("work_order_packages", "planning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            EstimatedHours = 8.5m,
                            PackageNumber = "PKG-1000",
                            PlannedEndUtc = new DateTimeOffset(new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PlannedStartUtc = new DateTimeOffset(new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PlanningRunId = new Guid("50000000-0000-0000-0000-000000000001"),
                            RecommendationRationale = "Combines ready work with the available access window.",
                            Status = "Recommended",
                            Title = "Pump seal work package"
                        });
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.Asset", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.FunctionalLocation", "FunctionalLocation")
                        .WithMany("Assets")
                        .HasForeignKey("FunctionalLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FunctionalLocation");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.IntegrationEvent", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.IntegrationImport", "IntegrationImport")
                        .WithMany("Events")
                        .HasForeignKey("IntegrationImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationImport");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.MajorEvent", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.Asset", "Asset")
                        .WithMany("MajorEvents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MaintenancePlanning.Domain.Planning.FunctionalLocation", "FunctionalLocation")
                        .WithMany("MajorEvents")
                        .HasForeignKey("FunctionalLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("FunctionalLocation");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PackageItem", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.WorkOrder", "WorkOrder")
                        .WithMany("PackageItems")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenancePlanning.Domain.Planning.WorkOrderPackage", "WorkOrderPackage")
                        .WithMany("Items")
                        .HasForeignKey("WorkOrderPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderPackage");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PlannerDecision", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.WorkOrder", "WorkOrder")
                        .WithMany("PlannerDecisions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MaintenancePlanning.Domain.Planning.WorkOrderPackage", "WorkOrderPackage")
                        .WithMany("Decisions")
                        .HasForeignKey("WorkOrderPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderPackage");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrder", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.Asset", "Asset")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MaintenancePlanning.Domain.Planning.FunctionalLocation", "FunctionalLocation")
                        .WithMany("WorkOrders")
                        .HasForeignKey("FunctionalLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("FunctionalLocation");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrderPackage", b =>
                {
                    b.HasOne("MaintenancePlanning.Domain.Planning.PlanningRun", "PlanningRun")
                        .WithMany("Packages")
                        .HasForeignKey("PlanningRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanningRun");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.Asset", b =>
                {
                    b.Navigation("MajorEvents");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.FunctionalLocation", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("MajorEvents");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.IntegrationImport", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.PlanningRun", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrder", b =>
                {
                    b.Navigation("PackageItems");

                    b.Navigation("PlannerDecisions");
                });

            modelBuilder.Entity("MaintenancePlanning.Domain.Planning.WorkOrderPackage", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
